// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC554gc99HdIza9abBVgpSj2cWp5hHG_FA',
    appId: '1:454043411099:web:b5d5469f4f57382d039c3e',
    messagingSenderId: '454043411099',
    projectId: 'hackatonutb',
    authDomain: 'hackatonutb.firebaseapp.com',
    storageBucket: 'hackatonutb.firebasestorage.app',
    measurementId: 'G-L8H743E793',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxdEi1LRJJMTeB32X2A76LeI2RMzU-Nb8',
    appId: '1:454043411099:android:1a8f96b04152ad8c039c3e',
    messagingSenderId: '454043411099',
    projectId: 'hackatonutb',
    storageBucket: 'hackatonutb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBezFk2QYUWLZY3KaSWvcrqX_vQsnseenY',
    appId: '1:454043411099:ios:e8b002584e67b827039c3e',
    messagingSenderId: '454043411099',
    projectId: 'hackatonutb',
    storageBucket: 'hackatonutb.firebasestorage.app',
    iosBundleId: 'com.example.ecoManage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBezFk2QYUWLZY3KaSWvcrqX_vQsnseenY',
    appId: '1:454043411099:ios:e8b002584e67b827039c3e',
    messagingSenderId: '454043411099',
    projectId: 'hackatonutb',
    storageBucket: 'hackatonutb.firebasestorage.app',
    iosBundleId: 'com.example.ecoManage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC554gc99HdIza9abBVgpSj2cWp5hHG_FA',
    appId: '1:454043411099:web:e9464da51ccbc56c039c3e',
    messagingSenderId: '454043411099',
    projectId: 'hackatonutb',
    authDomain: 'hackatonutb.firebaseapp.com',
    storageBucket: 'hackatonutb.firebasestorage.app',
    measurementId: 'G-QJ889F3E4V',
  );
}
